### ISSUE TITLE
Failure on pull request event

### ISSUE THREAD

**Issue by andrzej-kodify** [packtracker/report#4]
```
packtracker: webpack config file not found
packtracker: loading github config
/github/workspace/report.js:46
    branch: event.ref.replace('refs/heads/', ''),
                      ^

TypeError: Cannot read property 'replace' of undefined
    at githubConfig (/github/workspace/report.js:46:23)
    at Object.<anonymous> (/github/workspace/report.js:25:45)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11
##[error]Docker run failed with exit code 1
```

This event has different structure

**Comment by jondavidjohn** [comment]
Yes, currently we only support the on push event.
